<?php
/**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
if (!defined('_PS_VERSION_')) {
    exit;
}
class AdminDPDFranceControllerOverride extends AdminDPDFranceController
{
    /**
     * {@inheritdoc}
     * @param $isNewTheme
     */
    public function setMedia($isNewTheme = false)
    {
        parent::setMedia($isNewTheme);

        $this->addJS(_PS_THEME_DIR_.'modules/dpdfrance/views/js/dpd_codeam_addon.js');
    }

    public function renderView()
    {
        if (Tools::getIsset('updateStateToShipped')) {
            if (Tools::getIsset('checkbox')) {
                try {
                    $orders = Tools::getValue('checkbox');

                    if (is_string($orders)) {
                        $orders = explode(',', $orders);
                    }
                    if (!empty($orders)) {
                        $sql = new DbQuery();
                        $sql->select('id_order')
                            ->from('orders', 'O')
                            ->from('carrier', 'CA')
                            ->where('CA.id_carrier = O.id_carrier')
                            ->where('id_order IN (' . implode(',', array_map('intval', $orders)) . ')');
                        $orderlist = Db::getInstance()->executeS($sql);
                        if (!empty($orderlist)) {
                            // Check if there are DPD orders
                            foreach ($orderlist as $orders) {
                                $id_order = $orders['id_order'];
                                if (Validate::isLoadedObject($order = new Order($id_order))) {
                                    $history = new OrderHistory();
                                    $history->id_order = (int)$id_order;
                                    $history->id_order_state = DPDConfig::get('DPDFRANCE_ETAPE_EXPEDIEE', null, null, (int)$order->id_shop;
                                    $history->changeIdOrderState(DPDConfig::get('DPDFRANCE_ETAPE_EXPEDIEE', null, null, (int)$order->id_shop, $id_order);
                                    $history->id_employee = Context::getContext()->employee->id;
                                    $history->addWithemail();
                                }
                            }
                        }
                    }
                } catch (Exception $e) {

                }
            }
        }
        return parent::renderView();
    }
}
