<?php
/**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

class DPDFranceOverride extends DPDFrance
{
    public function install(): bool
    {
        parent::install();

        // BASIC CONFIG
        Configuration::updateValue('DPDFRANCE_PARAM', '1', true);
        Configuration::updateValue('DPDFRANCE_NOM_EXP', '', true);
        Configuration::updateValue('DPDFRANCE_ADDRESS_EXP', '', true);
        Configuration::updateValue('DPDFRANCE_ADDRESS2_EXP', NULL, true);
        Configuration::updateValue('DPDFRANCE_CP_EXP', '', true);
        Configuration::updateValue('DPDFRANCE_VILLE_EXP', '', true);
        Configuration::updateValue('DPDFRANCE_TEL_EXP', '', true);
        Configuration::updateValue('DPDFRANCE_GSM_EXP', NULL, true);
        Configuration::updateValue('DPDFRANCE_EMAIL_EXP', 'infos@france.com', true);
        Configuration::updateValue('DPDFRANCE_RELAIS_CARRIER_ID', '0', true);
        Configuration::updateValue('DPDFRANCE_RELAIS_DEPOT_CODE', '0', true);
        Configuration::updateValue('DPDFRANCE_RELAIS_SHIPPER_CODE', '0', true);
        Configuration::updateValue('DPDFRANCE_PREDICT_CARRIER_ID', '0', true);
        Configuration::updateValue('DPDFRANCE_PREDICT_DEPOT_CODE', '0', true);
        Configuration::updateValue('DPDFRANCE_PREDICT_SHIPPER_CODE', '0', true);
        Configuration::updateValue('DPDFRANCE_CLASSIC_CARRIER_ID', NULL, true);
        Configuration::updateValue('DPDFRANCE_CLASSIC_DEPOT_CODE', '0', true);
        Configuration::updateValue('DPDFRANCE_CLASSIC_SHIPPER_CODE', '0', true);
        Configuration::updateValue('DPDFRANCE_WEBTRACE_LOGIN', getenv('DPDFRANCE_WEBTRACE_LOGIN'), true);
        Configuration::updateValue('DPDFRANCE_WEBTRACE_PASSWORD', getenv('DPDFRANCE_WEBTRACE_PASSWORD'), true);
        Configuration::updateValue('DPDFRANCE_API_LOGIN', getenv('DPDFRANCE_API_LOGIN'), true);
        Configuration::updateValue('DPDFRANCE_API_PASSWORD', getenv('DPDFRANCE_API_PASSWORD'), true);
        Configuration::updateValue('DPDFRANCE_DAY_DEFINITE_MODE', '0', true);
        Configuration::updateValue('DPDFRANCE_LEADTIME_API_KEY', NULL, true);
        Configuration::updateValue('DPDFRANCE_SUPP_ILES', '19', true);
        Configuration::updateValue('DPDFRANCE_SUPP_MONTAGNE', '6', true);
        Configuration::updateValue('DPDFRANCE_GOOGLE_API_KEY', NULL, true);
        Configuration::updateValue('DPDFRANCE_FORMAT_MOD', 'pdf', true);
        Configuration::updateValue('DPDFRANCE_PRINTER_CONNECT', 'usb', true);
        Configuration::updateValue('DPDFRANCE_PRINTER_PORT', NULL, true);
        Configuration::updateValue('DPDFRANCE_PRINTER_IP', NULL, true);
        Configuration::updateValue('DPDFRANCE_HIDE_NETWORK', NULL, true);
        Configuration::updateValue('DPDFRANCE_PRINTER_SERIAL', NULL, true);
        Configuration::updateValue('DPDFRANCE_FORMAT_PRINT', 'a6', true);
        Configuration::updateValue('DPDFRANCE_SERVICE_TYPE', 'e_print', true);
        Configuration::updateValue('DPDFRANCE_ETAPE_EXPEDITION', '25', true);
        Configuration::updateValue('DPDFRANCE_ETAPE_EXPEDIEE', '4', true);
        Configuration::updateValue('DPDFRANCE_ETAPE_LIVRE', '5', true);
        Configuration::updateValue('DPDFRANCE_AD_VALOREM', '0', true);
        Configuration::updateValue('DPDFRANCE_AUTO_UPDATE', '2', true);
        Configuration::updateValue('DPDFRANCE_MARKETPLACE_MODE', '0', true);
        Configuration::updateValue('DPDFRANCE_RETOUR_OPTION', '0', true);
        Configuration::updateValue('DPDFRANCE_LAST_TRACKING', '0', true);
        Configuration::updateValue('DPDFRANCE_RELAIS_CARRIER_LOG', '', true);
        Configuration::updateValue('DPDFRANCE_PREDICT_CARRIER_LOG', '', true);
        Configuration::updateValue('DPDFRANCE_RELAIS_MYPUDO_URL', 'http://mypudo.pickup-services.com/mypudo/mypudo.asmx?WSDL', true);

        return true;
    }
}
